### ISSUE TITLE
[Roadmap] Road to v1.0.0

### ISSUE THREAD

**Issue by HeadFox** [HeadFox/npm-update-tool#2]
- [ ] Support json/rc config file
- [x] Support excludes
- [x] Support excludesQuality
- [ ] Add unit tests
- [ ] Support custom qualityTest
- [ ] Support for regex for filter
